# Generated by Django 2.0 on 2018-01-31 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0002_auto_20180131_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='footer',
            field=models.CharField(max_length=256),
        ),
    ]
