# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-24 01:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='job51',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=256)),
                ('company', models.CharField(max_length=512)),
                ('address', models.CharField(max_length=512)),
                ('wages', models.CharField(max_length=256)),
                ('date', models.CharField(max_length=256)),
                ('jobname', models.CharField(max_length=256)),
                ('joburl', models.CharField(max_length=512)),
                ('jobtxt', models.CharField(blank=True, max_length=512)),
                ('jobaddress', models.CharField(max_length=256)),
            ],
        ),
    ]
