# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-12 07:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job51', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job51',
            name='address',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='job51',
            name='commpany',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='job51',
            name='joburl',
            field=models.CharField(max_length=512),
        ),
    ]
