# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-12 09:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job51', '0002_auto_20180312_1534'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job51',
            old_name='commpany',
            new_name='company',
        ),
    ]
