# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-03-12 09:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job51', '0005_auto_20180312_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job51',
            name='jobtxt',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
