# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-12 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageViewStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_week', models.CharField(choices=[('1', '周一'), ('2', '周二'), ('3', '周三'), ('4', '周四'), ('5', '周五'), ('6', '周六'), ('7', '周日')], max_length=100)),
                ('view_way', models.CharField(choices=[('邮件营销', '邮件营销'), ('联盟广告', '联盟广告'), ('视频广告', '视频广告'), ('直接访问', '直接访问'), ('搜索引擎', '搜索引擎')], max_length=256)),
                ('page_views', models.IntegerField()),
                ('pub_date', models.DateField()),
            ],
            options={
                'db_table': 'pv_statistics',
            },
        ),
    ]
