# Generated by Django 2.0 on 2018-01-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('StuApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabname',
            name='Num',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='urldb',
            name='Num',
            field=models.IntegerField(),
        ),
    ]
